### ISSUE TITLE
ISSUE_TEMPLATE/bug-report.yml could link to Harlowe's bug tracker

### ISSUE THREAD

**Issue by webbedspace** [klembot/twinejs#1242]
The line "If you are having problems with your Twine story when it is being played, then you should report the problem with the story format you are using, not here." could possibly include a link to Harlowe's bug tracker (which is at https://foss.heptapod.net/games/harlowe/-/issues ) in a separate sentence afterward. Could save people a few clicks.

### Presubmission checklist

- [X] I am interested in working on code that would implement this feature request. (This is not required to submit a suggestion.)
- [X] I have done a search and believe that an issue does not already exist for this idea in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by klembot** [comment]
Sounds good to me... how about a bulleted list under that line? PR would be welcome if you have the time.

**Comment by klembot** [comment]
Resolved by https://github.com/klembot/twinejs/pull/1251
